### 상영 중인 영화 조회
POST localhost:8080/api/v1/movies/now-showing
Content-Type: application/json

{
  "movieName": {
    "value": "극한직업",
    "type": "EQUAL"
  },
  "genre": ["ACTION"],
  "status": ["SHOWING"],
  "isReleaseDateAsc": true
}