services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=skillup'
      - 'MYSQL_PASSWORD=skillup'
      - 'MYSQL_ROOT_PASSWORD=skillup'
      - 'MYSQL_USER=skillup'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
