plugins {
    id 'java-library'
}

dependencies {
    implementation project(':module-domain')
    implementation project(':module-common')

    // JPA 및 데이터베이스 접근 의존성
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'
    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    // Lombok과 MapStruct 함께 사용 시 필요
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
}