CREATE TABLE booking
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_id BIGINT,
    seat_id     BIGINT,
    created_by  VARCHAR(255),
    created_at  TIMESTAMP,
    updated_by  VARCHAR(255),
    updated_at  TIMESTAMP,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE genre
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE movie
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    thumbnailurl VARCHAR(255),
    release_date date,
    duration     INT                                     NOT NULL,
    genre_id     BIGINT,
    rating       VARCHAR(255),
    created_by   VARCHAR(255),
    created_at   TIMESTAMP,
    updated_by   VARCHAR(255),
    updated_at   TIMESTAMP,
    CONSTRAINT pk_movie PRIMARY KEY (id)
);

CREATE TABLE seat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    CONSTRAINT pk_seat PRIMARY KEY (id)
);

CREATE TABLE showtime
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theater_id BIGINT,
    movie_id   BIGINT,
    start_time time,
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    CONSTRAINT pk_showtime PRIMARY KEY (id)
);

CREATE TABLE theater
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    CONSTRAINT pk_theater PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seat (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_SHOWTIME FOREIGN KEY (showtime_id) REFERENCES showtime (id);

ALTER TABLE movie
    ADD CONSTRAINT FK_MOVIE_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE showtime
    ADD CONSTRAINT FK_SHOWTIME_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movie (id);

ALTER TABLE showtime
    ADD CONSTRAINT FK_SHOWTIME_ON_THEATER FOREIGN KEY (theater_id) REFERENCES theater (id);