spring:
  profiles:
    active: application
  application:
    name: cinema
  datasource:
    url: jdbc:mysql://localhost:33306/cinema?useUnicode=true&character_set_server=utf8mb4&collation=utf8mb4_general_ci
    username: user
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: trace

cache:
  local:
    max-size: 1000 # 캐시 최대 1000개까지 저장 가능
    expire-after-write: PT10M  # 캐시 만료 기본 시간 (10분)
  global:
    expire-after-write: PT10M
